version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    assignees:
      - antonplagemann
    reviewers:
      - antonplagemann
    target-branch: main

  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: daily
    assignees:
      - antonplagemann
    reviewers:
      - antonplagemann
    target-branch: main

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - antonplagemann
    reviewers:
      - antonplagemann
    target-branch: main
