name: update-room-plan

on:
  schedule:
    - cron: "0 5 * * 1-5" # runs at 05:00 UTC every day (no weekends)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # install the python version needed

      - name: install python packages
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python script # run parse.py to get the latest data
        run: |
          cd python
          python parse.py

      - name: build vue app # Rebuild the website
        run: |
              npm ci
              npm run build
              cd docs
              ln -s index.html 404.html
              echo 'rooms.plagemann.it' > CNAME
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add -A
              git commit -m "Update room plan resources" -a
              git push
        shell: bash
